=== hamdiakin/latest-converter/src/main/resources/TA.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:simpleType name="XsdPositiveInteger">

        <xsd:restriction base="xsd:integer">

            <xsd:minInclusive value="1"/>

            <xsd:maxInclusive value="1073741823"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="XsdNonNegativeInteger">

        <xsd:restriction base="xsd:integer">

            <xsd:minInclusive value="0"/>

            <xsd:maxInclusive value="1073741823"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="XsdIntegerBufferCapacity">

        <xsd:restriction base="xsd:integer">

            <xsd:minInclusive value="0"/>

            <xsd:maxInclusive value="20000000"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="XsdHost">

        <xsd:restriction base="xsd:string">

            <xsd:pattern value="([0-9]*[0-9.])*"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="XsdClassName">

        <xsd:restriction base="xsd:string">

            <xsd:pattern value="([a-zA-Z]([a-zA-Z0-9_]*))"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="XsdAttributeName">

        <xsd:restriction base="xsd:string">

            <xsd:pattern value="([a-zA-Z_]([a-zA-Z0-9_]*))"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="XsdPackageName">

        <xsd:restriction base="xsd:string">

            <xsd:pattern value="([a-zA-Z]*([a-zA-Z0-9._]*))*"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="XsdFormat">

        <xsd:restriction base="xsd:string">

            <xsd:enumeration value="CB2"/>

            <xsd:enumeration value="BNR"/>

            <xsd:enumeration value="BNR_S"/>

            <xsd:enumeration value="BCD"/>

            <xsd:enumeration value="BCD_S"/>

            <xsd:enumeration value="STR"/>

            <xsd:enumeration value="IEEEFloat"/>

            <xsd:enumeration value="IEEEDouble"/>

            <xsd:enumeration value="CUSTOM"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="XsdBitIndex">

        <xsd:restriction base="xsd:integer">

            <xsd:minInclusive value="0"/>

            <xsd:maxInclusive value="7"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- ********************************TA CONFIGURATION*********************************** -->
    <xsd:element name="TA" type="XsdTa">
    </xsd:element>

    <xsd:complexType name="XsdTa">

        <xsd:sequence>
            <xsd:element name="types" type="XsdTypes"/>
            <xsd:element name="messages" type="XsdMessages"/>
            <xsd:element name="codecs" type="XsdCodecs"/>
        </xsd:sequence>

        <xsd:attribute name="rootPackagePrefix" type="XsdPackageName"
                       use="required"/>
    </xsd:complexType>

    <xsd:complexType name="XsdMessages">
        <xsd:sequence>
            <xsd:element name="message" minOccurs="0" maxOccurs="unbounded"
                         type="XsdMessage"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="XsdCodecs">
        <xsd:sequence>
            <xsd:element name="codec" maxOccurs="unbounded" type="XsdCodec"/>
        </xsd:sequence>
    </xsd:complexType>
    <!-- ********************************TYPE DEFINITIONS******************************** -->

    <xsd:complexType name="XsdTypes">
        <xsd:sequence>
            <xsd:element name="primitive" maxOccurs="unbounded"
                         minOccurs="0" type="XsdPrimitive"/>
            <xsd:element name="enum" maxOccurs="unbounded" minOccurs="0"
                         type="XsdEnum"/>
            <xsd:element name="structure" maxOccurs="unbounded"
                         minOccurs="0" type="XsdStructure"/>
            <xsd:element name="array" maxOccurs="unbounded"
                         minOccurs="0" type="XsdArray"/>
            <xsd:element name="list" maxOccurs="unbounded"
                         minOccurs="0" type="XsdList"/>
            <xsd:element name="union" maxOccurs="unbounded"
                         minOccurs="0" type="XsdUnion"/>
            <xsd:element name="compound" maxOccurs="unbounded" minOccurs="0" type="XsdCompound"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="XsdPrimitiveType">

        <xsd:restriction base="xsd:string">

            <xsd:enumeration value="boolean"/>

            <xsd:enumeration value="char"/>

            <xsd:enumeration value="byte"/>

            <xsd:enumeration value="short"/>

            <xsd:enumeration value="int"/>

            <xsd:enumeration value="long"/>

            <xsd:enumeration value="float"/>

            <xsd:enumeration value="double"/>

            <xsd:enumeration value="String"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="XsdTypeEnum">

        <xsd:restriction base="xsd:string">

            <xsd:enumeration value="PRIMITIVE"/>

            <xsd:enumeration value="ENUM"/>

            <xsd:enumeration value="STRUCTURE"/>

            <xsd:enumeration value="ARRAY"/>

            <xsd:enumeration value="LIST"/>

            <xsd:enumeration value="UNION"/>

            <xsd:enumeration value="COMPOUND"/>

        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="XsdType">
        <xsd:sequence>
            <xsd:element name="typeEnum" minOccurs="0" type="XsdTypeEnum"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="XsdPrimitive">
        <xsd:complexContent>
            <xsd:extension base="XsdType">
                <xsd:attribute name="name" type="xsd:string" use="required"/>

                <xsd:attribute name="type" type="XsdPrimitiveType" use="required"/>

                <xsd:attribute name="format" type="XsdFormat" use="required"/>

                <xsd:attribute name="sizeInBytes" type="XsdNonNegativeInteger" use="required"/>

                <xsd:attribute name="sizeInBits" type="XsdNonNegativeInteger" use="required"/>

                <xsd:attribute name="min" type="xsd:anySimpleType" use="optional"/>

                <xsd:attribute name="max" type="xsd:anySimpleType" use="optional"/>

                <xsd:attribute name="resolution" type="XsdResolution" default="1.0" use="optional"/>

                <xsd:attribute name="translatorClass" type="xsd:string" use="optional"/>

                <xsd:attribute name="boundCheck" type="xsd:boolean" default="true"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="XsdEnum">
        <xsd:complexContent>
            <xsd:extension base="XsdType">
                <xsd:sequence maxOccurs="unbounded" minOccurs="1">

                    <xsd:element name="enumVariable" type="XsdEnumVariable"/>
                </xsd:sequence>

                <xsd:attribute name="name" type="XsdClassName" use="required"/>

                <xsd:attribute name="format" type="XsdFormat" use="required"/>

                <xsd:attribute name="sizeInBytes" type="XsdNonNegativeInteger"
                               use="required"/>

                <xsd:attribute name="sizeInBits" type="XsdNonNegativeInteger"
                               use="required"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="XsdEnumVariable">

        <xsd:attribute name="name" type="xsd:string" use="required"/>

        <xsd:attribute name="value" type="xsd:int" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="XsdStructure">
        <xsd:complexContent>
            <xsd:extension base="XsdType">
                <xsd:sequence>

                    <xsd:element name="field" maxOccurs="unbounded"
                                 minOccurs="1" type="XsdField"/>
                </xsd:sequence>

                <xsd:attribute name="name" type="XsdAttributeName" use="required"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="XsdArray">
        <xsd:complexContent>
            <xsd:extension base="XsdType">
                <xsd:attribute name="name" type="XsdAttributeName" use="required"/>

                <xsd:attribute name="elementType" type="xsd:string" use="required"/>

                <xsd:attribute name="constantElementCount" type="XsdNonNegativeInteger" use="optional" default="0"/>

                <xsd:attribute name="delimiter" type="xsd:string" use="optional" default="null"/>

                <xsd:attribute name="UseExtensionIndicator" type="xsd:boolean" use="optional" default="false"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="XsdList">
        <xsd:complexContent>
            <xsd:extension base="XsdType">
                <xsd:attribute name="name" type="XsdAttributeName" use="required"/>

                <xsd:attribute name="elementType" type="xsd:string" use="required"/>

                <xsd:attribute name="constantElementCount" type="XsdNonNegativeInteger" use="optional" default="0"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="XsdUnion">
        <xsd:complexContent>
            <xsd:extension base="XsdType">
                <xsd:sequence>
                    <xsd:element name="field" maxOccurs="unbounded"
                                 minOccurs="1" type="XsdUnionField"/>
                </xsd:sequence>

                <xsd:attribute name="name" type="XsdAttributeName" use="required"/>
                <xsd:attribute name="discriminantType" type="XsdAttributeName"
                               use="required"/>
                <xsd:attribute name="maxLengthHolder" type="xsd:boolean"
                               use="optional" default="true"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="XsdUnionField">
        <xsd:attribute name="name" type="XsdAttributeName" use="required"/>
        <xsd:attribute name="type" type="xsd:string" use="required"/>
        <xsd:attribute name="discriminantValue" type="xsd:string"
                       use="required"/>
    </xsd:complexType>

    <xsd:complexType name="XsdCompound">
        <xsd:complexContent>
            <xsd:extension base="XsdType">
                <xsd:sequence minOccurs="1" maxOccurs="1">
                    <xsd:element name="lookUp" type="XsdCompoundLookUp" minOccurs="1" maxOccurs="1"/>
                    <xsd:element name="fields" type="XsdCompoundFields" minOccurs="1" maxOccurs="1"/>
                </xsd:sequence>

                <xsd:attribute name="name" type="XsdAttributeName" use="required"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="XsdCompoundLookUp">

        <xsd:sequence>
            <xsd:element name="field" maxOccurs="unbounded" minOccurs="1" type="XsdField"/>
        </xsd:sequence>

    </xsd:complexType>

    <xsd:complexType name="XsdCompoundFields">

        <xsd:sequence>
            <xsd:element name="field" maxOccurs="unbounded" minOccurs="1" type="XsdField"/>
        </xsd:sequence>

    </xsd:complexType>
    <!-- ********************************CODEC CONFIGURATION******************************** -->

    <xsd:complexType name="XsdCodec">
        <xsd:sequence>
            <xsd:element name="header" type="XsdHeader"/>
            <xsd:element name="footer" type="XsdFooter"/>
            <xsd:element name="message" maxOccurs="unbounded" minOccurs="0" type="XsdCodecMessage"/>
        </xsd:sequence>

        <xsd:attribute name="name" type="XsdClassName" use="required"/>

        <xsd:attribute name="byteOrder" type="XsdByteOrder" default="BIG_ENDIAN"/>

        <xsd:attribute name="inputBufferCapacity" type="XsdIntegerBufferCapacity" default="500000"/>

        <xsd:attribute name="outputBufferCapacity" type="XsdIntegerBufferCapacity" default="500000"/>

    </xsd:complexType>

    <xsd:simpleType name="XsdByteOrder">
        <xsd:restriction base="xsd:string">

            <xsd:enumeration value="BIG_ENDIAN"/>

            <xsd:enumeration value="LITTLE_ENDIAN"/>

        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="XsdResolution">
        <xsd:restriction base="xsd:double">
            <xsd:minInclusive value="0.0"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="XsdCodecMessage">
        <xsd:attribute name="name" type="XsdClassName" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="XsdHeader">
        <xsd:sequence>
            <xsd:element name="field" maxOccurs="unbounded" minOccurs="0" type="XsdField"/>
        </xsd:sequence>

        <xsd:attribute name="imports" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="XsdFooter">
        <xsd:sequence>
            <xsd:element name="field" maxOccurs="unbounded"
                         minOccurs="0" type="XsdField"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- ********************************MESSAGE CONFIGURATION******************************** -->

    <xsd:complexType name="XsdMessage">
        <xsd:sequence>
            <xsd:element name="field" maxOccurs="unbounded" minOccurs="0" type="XsdField"/>
        </xsd:sequence>

        <xsd:attribute name="id" type="xsd:int" use="required"/>
        <xsd:attribute name="name" type="XsdClassName" use="required"/>
        <xsd:attribute name="imports" type="xsd:string" use="optional"/>

    </xsd:complexType>


    <xsd:simpleType name="XsdFieldProperty"> <!-- Keep synchronized with "FieldPropertyEnum.java"! -->

        <xsd:restriction base="xsd:string">

            <xsd:enumeration value="None"/>

            <xsd:enumeration value="Preamble"/>

            <xsd:enumeration value="Id"/>

            <xsd:enumeration value="PayloadSize"/>

            <xsd:enumeration value="TotalSize"/>

            <xsd:enumeration value="CalculatedSize"/>

            <xsd:enumeration value="Postamble"/>

            <xsd:enumeration value="Delimiter"/>

            <xsd:enumeration value="Checksum"/>

            <xsd:enumeration value="Extension"/>

            <xsd:enumeration value="PresenceIndicator"/>

        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="XsdSizeUnit">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="BYTE"/>
            <xsd:enumeration value="WORD"/>
            <xsd:enumeration value="DWORD"/>
            <xsd:enumeration value="QWORD"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="XsdField">

        <xsd:attribute name="name" type="XsdAttributeName" use="required"/>

        <xsd:attribute name="type" type="xsd:string" use="required"/>

        <xsd:attribute name="defaultValue" type="xsd:string" default="" use="optional"/>

        <xsd:attribute name="optional" default="false" type="xsd:boolean" use="optional"/>
        <!-- Default elementCount=0 means array is variable length -->

        <xsd:attribute name="constantElementCount" default="0" type="XsdNonNegativeInteger" use="optional"/>

        <xsd:attribute name="delimiter" default="null" type="xsd:string" use="optional"/>

        <xsd:attribute name="discriminantField" default="_" type="xsd:string" use="optional"/>

        <xsd:attribute name="elementCountField" default="-1" type="xsd:string" use="optional"/>

        <xsd:attribute name="fieldProperty" type="XsdFieldProperty" use="optional" default="None"/>

        <xsd:attribute name="sizeUnit" type="XsdSizeUnit" use="optional" default="BYTE"/>

        <xsd:attribute name="fieldIndex" type="XsdNonNegativeInteger" use="required"/>

        <xsd:attribute name="lookUpField" type="xsd:string" use="optional"/>

        <xsd:attribute name="annotations" type="xsd:string" use="optional"/>

        <xsd:attribute name="parameterName" type="xsd:string" use="optional"/>

        <xsd:attribute name="elementCountParameter" type="xsd:string" use="optional"/>

        <!-- if fieldProperty == CalculatedSize one of this attributes is required.-->
        <xsd:attributeGroup ref="CalculatedSizeAttributes"/>

    </xsd:complexType>

    <xsd:attributeGroup name="CalculatedSizeAttributes">
        <xsd:attribute name="calculatedSizeFormula" type="xsd:string" use="optional"/>
        <xsd:attribute name="payloadSizeFormula" type="xsd:string" use="optional"/>
    </xsd:attributeGroup>

</xsd:schema>

=== hamdiakin/latest-converter/xmlOut.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TA.xsd">
    
    <types>
        <primitive byteOrder="byte" id="BNR" name="BYTE" size="8" type="0"/>
        <primitive byteOrder="int" id="BNR" name="UINT_8" size="8" type="0"/>
        <primitive byteOrder="String" id="STR" name="STRING_10CHAR" size="0" type="10"/>
        <primitive byteOrder="String" id="STR" name="STRING_VARSIZE" size="0" type="1"/>
        <primitive byteOrder="char" id="CB2" name="CHAR" size="8" type="0"/>
        
        <structure name=""/>
        
        <arrayType constantElementCount="" elementType="BYTE" name="CheckSumArray"/>
        <arrayType constantElementCount="" elementType="BYTE_CB2" name="CharArray"/>
        <arrayType constantElementCount="" elementType="UINT_8" name="UINT_8_Array"/>
        <arrayType constantElementCount="" elementType="UINT_8" name="UINT_8_Array_Len3"/>
        <arrayType constantElementCount="" elementType="STRUCT1" name="STRUCT1_Array_VarSize"/>
        <arrayType constantElementCount="" elementType="STRUCT1" name="STRUCT1_Array_ConstSize3"/>
        <arrayType constantElementCount="" elementType="CHAR" name="CharTypeArray"/>
        <arrayType constantElementCount="" elementType="BYTE" name="PreambleNoConstSizeArray"/>
    </types>
    
    <messages>
        <message id="2" name="Message2">
            <field fieldIndex="0" name="field0" type="UINT_8"/>
            <field fieldIndex="1" name="field1" type="UINT_8"/>
            <field fieldIndex="2" name="field2" type="UINT_8"/>
        </message>
        
        <message id="3" name="Message3">
            <field fieldIndex="0" name="field0" type="UINT_8"/>
            <field fieldIndex="1" name="field1" type="UINT_8"/>
            <field fieldIndex="2" name="field2" type="UINT_8"/>
        </message>
        
        <message id="4" name="Message4">
            <field fieldIndex="0" name="field0" type="UINT_8"/>
            <field fieldIndex="1" name="field1" type="UINT_8"/>
            <field fieldIndex="2" name="field2" type="UINT_8"/>
            <field fieldIndex="3" name="field3" type="UINT_8"/>
        </message>
        
        <message id="5" name="Message5">
            <field fieldIndex="0" name="field0" type="STRING_10CHAR"/>
            <field fieldIndex="1" name="field1" type="STRING_10CHAR"/>
            <field fieldIndex="2" name="field2" type="STRING_10CHAR"/>
            <field fieldIndex="3" name="field3" type="STRING_10CHAR"/>
        </message>
        
        <message id="6" name="Message6">
            <field fieldIndex="0" name="field0" type="UINT_8"/>
            <field elementCountMessageField="field0" fieldIndex="1" name="field1" type="CharArray"/>
        </message>
        
        <message id="7" name="Message7">
            <field fieldIndex="0" name="field0" type="UINT_8"/>
            <field elementCountMessageField="field0" fieldIndex="1" name="field1" type="STRUCT1_Array_VarSize"/>
        </message>
        
        <message id="8" name="Message8">
            <field fieldIndex="0" name="field0" type="UINT_8"/>
            <field fieldIndex="1" name="field1" type="STRUCT1_Array_ConstSize3"/>
        </message>
        
        <message id="9" name="Message9">
            <field fieldIndex="0" name="field0" type="UINT_8_Array"/>
        </message>
        
        <message id="10" name="Message10">
            <field fieldIndex="0" name="field0" type="UINT_8"/>
        </message>
        
        <message id="10" name="Message10"/>
        
    </messages>
    
    <codecs>
        
        <codec byteOrder="BIG_ENDIAN" name="EasyCodec_PrePost_BigEnd">
            <header>
                <field fieldIndex="0" fieldProperty="Preamble" name="msgPreamble" type="PrePostAmbleArray"/>
                <field fieldIndex="1" fieldProperty="Id" name="msgId" type="UINT_8"/>
            </header>
            <footer>
                <field fieldIndex="0" fieldProperty="Postamble" name="msgPostamble" type="PrePostAmbleArray"/>
            </footer>
            
            <message name="Message1"/>
            <message name="Message2"/>
            <message name="Message3"/>
            <message name="Message4"/>
            <message name="Message5"/>
            <message name="Message6"/>
            <message name="Message7"/>
            <message name="Message8"/>
            <message name="Message9"/>
            
        </codec>
        
        <codec byteOrder="BIG_ENDIAN" name="EasyCodec_IdLen_BigEnd_Checksum">
            <header>
                <field fieldIndex="0" fieldProperty="Id" name="msgId" type="UINT_8"/>
                <field fieldIndex="1" fieldProperty="TotalSize" name="msglength" type="UINT_8"/>
            </header>
            <footer>
                <field fieldIndex="0" fieldProperty="Checksum" name="msgChecksum" type="CheckSumArray"/>
            </footer>
            
            <message name="Message1"/>
            <message name="Message2"/>
            <message name="Message3"/>
            <message name="Message4"/>
            <message name="Message5"/>
            <message name="Message6"/>
            <message name="Message7"/>
            <message name="Message8"/>
            <message name="Message9"/>
            
        </codec>
        
        <codec byteOrder="BIG_ENDIAN" name="EasyCodec_Id_BigEnd_Checksum">
            <header>
                <field fieldIndex="0" fieldProperty="Id" name="msgId" type="UINT_8"/>
                <field fieldIndex="1" name="msgHeaderField0" type="UINT_8"/>
            </header>
            <footer>
                <field fieldIndex="0" fieldProperty="Checksum" name="msgChecksum" type="CheckSumArray"/>
            </footer>
            
            <message name="Message1"/>
            <message name="Message2"/>
            <message name="Message3"/>
            <message name="Message4"/>
            <message name="Message5"/>
            <message name="Message6"/>
            <message name="Message7"/>
            <message name="Message8"/>
            <message name="Message9"/>
            
        </codec>
        
        <codec byteOrder="BIG_ENDIAN" name="EasyCodec_IdLen_BigEnd_CalculatedSize">
            <header>
                <field fieldIndex="0" name="field0" type="UINT_8"/>
                <field fieldIndex="1" fieldProperty="CalculatedSize" name="length" type="UINT_8"/>
                <field fieldIndex="2" name="field2" type="UINT_8"/>
                <field fieldIndex="3" fieldProperty="Id" name="msgId" type="UINT_8"/>
            </header>
            <footer/>
            
            <message name="Message1"/>
            
        </codec>
        
        <codec byteOrder="BIG_ENDIAN" name="EasyCodec_IdLenPayload_BigEnd">
            <header>
                <field fieldIndex="0" fieldProperty="Id" name="msgId" type="UINT_8"/>
                <field fieldIndex="1" fieldProperty="PayloadSize" name="msglength" type="UINT_8"/>
            </header>
            <footer/>
            
            <message name="Message1"/>
            <message name="Message11"/>
            
        </codec>
        
        <codec byteOrder="BIG_ENDIAN" name="EasyCodec_IdLen_BigEnd_HeaderArray">
            <header>
                <field fieldIndex="0" fieldProperty="Id" name="msgId" type="UINT_8"/>
                <field fieldIndex="1" fieldProperty="TotalSize" name="msglength" type="UINT_8"/>
                <field fieldIndex="2" name="fieldHeaderArr" type="UINT_8_Array_Len3"/>
            </header>
            <footer/>
            
            <message name="Message1"/>
            
        </codec>
    </codecs>
    
</TA>
